services:
  open-webui-build:
    container_name: open-webui-build
    image: node:22
    volumes:
      - .:/app
    command:
      - bash
      - -c
      - |
        cd /app
        if [ ! -d "build/" ]; then
          npm install
          npm run build
        fi

  open-webui:
    image: open-webui
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
      - .:/app
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
    depends_on:
      - open-webui-build
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - /home/kneox/Documents/ssl:/home/kneox/Documents/ssl
    depends_on:
      - open-webui
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  open-webui: {}
  nginx: {}